name: Java CI

on: [push]

jobs:
  build: #job

    runs-on: ubuntu-latest

    steps:
    - run: echo ${{ secrets.TEST_VALUE }}
    - uses: actions/checkout@v1 #step
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1 #step
      with: #inputs
        java-version: 1.8
#        cache: gradle
    - name: Change wrapper permissions
      run: chmod +x ./gradlew #script
    - uses: gradle/gradle-build-action@v2
      with:
        arguments: build
#    - name: Build with Gradle
#      run: ./gradlew build --no-daemon
    - run: mkdir staging && cp build/libs/*.jar staging
    - uses: actions/upload-artifact@v3
      with:
        name: Package
        path: staging
    - name: Build Image
      run: mkdir image && cp docker build . image
    - uses: actions/upload-artifact@v3
      with:
        name: Image
        path: image

